# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_photo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='meta_description',
            field=models.CharField(default=False, help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='photo',
            name='meta_keywords',
            field=models.CharField(default=False, help_text='Comma-delimated set of SEO Keywords for meta tag', max_length=255, verbose_name='Meta Keywords'),
        ),
    ]
