# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('choice', models.CharField(choices=[('website', 'WebSite'), ('Photography', 'Wedding Photography'), ('Photography', 'Pre Wedding Photography'), ('Photography', 'Maternity Photography'), ('Photography', 'Portfolio'), ('Application Development', 'Android Application'), ('Application Development', 'Ios Application')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
