# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
