# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webdev', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webdev_Photo',
        ),
    ]
